baseURL = "https://0x00.wtf/"
languageCode = "en-us"
theme = "PaperMod"
paginate = "5" # Number of posts per page
googleAnalytics = "UA-157872730-1"
disqusShortname = "btree-fun"
title = "Rory's Island"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
title = "Rory's Island"
description = "Rory's life style and study"
keywords = [ "Blog", "Portfolio", "Moto" ]
author = "Rory"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = true
showtoc = false
tocopen = false

  [params.assets]
  favicon = "/favicon.png"
  favicon16x16 = "/favicon.png"
  favicon32x32 = "/favicon.png"
  apple_touch_icon = "/favicon.png"
  safari_pinned_tab = "/favicon.png"

  [params.label]
  text = "Rory's Island"
  icon = "/favicon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "Rory's Island"
  subtitle = "This is subtitle"
  imageUrl = "<img location>"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = """
  - Welcome to Rory's Island.
  - More info [about me](/about)
  """

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/hola_rory"

  [[params.socialIcons]]
  name = "stackoverflow"
  url = "https://stackoverflow.com"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/gongzili456"

[params.analytics.google]
SiteVerificationTag = "UA-157872730-1"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/gongzili456/btree.fun/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 1

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
identifier = "ride"
name = "Ride"
url = "/ride/"
weight = 4

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 5

[markup.highlight]
noClasses = false

[markup.goldmark.renderer]
unsafe = true

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true


